print('Assalamy aleykum')
fjdskafds
f
dasfjdaskfjdaskfads
fkdjsfjdsjfsad
fkadsfjdskfjkdsjfas
fsdkfjadksfjkdsjfdsaf
jkadsjfjadskfjadsf
adsfkjdjsfjdsa
asfdskajfadsf
dsfjkdsjfdskljfkds
sadfjadskfjkasj

print('Ya aleykum assalam')
jfadsfkf
asfkjdsajfkdsjfksda
fdkjfsjakfjdskfdsa
fkjdsfjkdsjfsda
fkfjdsaklfj
fkasjfdskf
safkdsfjkdsjfjds
fjdskfjkdsjfkdsjfkds